version: "3.9"

volumes:
  data: {}

services:
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=development
      - POSTGRES_USER=rails
      - POSTGRES_PASSWORD=rails
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data

  rails:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - RAILS_ENV=development
      - SENDGRID_USERNAME
      - SENDGRID_PASSWORD
      - IEX_PUBLIC
      - IEX_SECRET
      - GOOGLE_CALENDAR_ID=5hmtac0npqm3k8qi9l2fpq0ipg@group.calendar.google.com
      - GOOGLE_CALENDAR_KEY=AIzaSyBhs9X1ThSmpEC1YOZkfwgH0IN0G6StiKg
    stdin_open: true
    tty: true
