version: "3.9"

volumes:
  data: {}
  redis-data: {}

services:
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=development
      - POSTGRES_USER=rails
      - POSTGRES_PASSWORD=rails
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data

  redis:
    image: redis:7.0-rc2-alpine
    entrypoint: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

  sidekiq:
    depends_on:
      - postgres
      - redis
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/myapp
    environment:
      - REDIS_URL=redis://redis:6379/0

  rails:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - sidekiq
    environment:
      - RAILS_ENV=development
      - SENDGRID_USERNAME
      - SENDGRID_PASSWORD
      - IEX_PUBLIC
      - IEX_SECRET
      - GOOGLE_CALENDAR_ID
      - GOOGLE_CALENDAR_KEY
      - REDIS_URL=redis://redis:6379/0
    stdin_open: true
    tty: true
