version: "3.9"

volumes:
  data: {}

services:
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=development
      - POSTGRES_USER=rails
      - POSTGRES_PASSWORD=rails
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data

  rails:
    build: .
    image: 068759620473.dkr.ecr.us-east-1.amazonaws.com/rails
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=production
      - SENDGRID_USERNAME
      - SENDGRID_PASSWORD
      - IEX_PUBLIC
      - IEX_SECRET
      - GOOGLE_CALENDAR_ID
      - GOOGLE_CALENDAR_KEY
      - DATABASE_NAME
      - DATABASE_HOST
      - DATABASE_PASSWORD
      - DATABASE_USER
      - SECRET_KEY_BASE=empty
    stdin_open: true
    tty: true
