default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: postgres
  database: development
  username: rails
  password: rails

test:
  <<: *default
  database: test
  password:

production:
  <<: *default
  database: ddcl8rl83l5a2d
  username: hlfcmkjcyybvep
  password:
