name: Puplish Image to ECR

on:
  push:
    branches: [ master ]
  pull_request:
    types:
      - labeled

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'ci-test' }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker-compose build rails
          docker-compose push rails-service
